"""Turn the raw result files into the tables and plot coordinates used in
the paper.

Outputs
    results/summary.csv          one row per variant and evaluation length
    results/depth_profile.csv    recall against needle depth
    results/pgfplots.txt         coordinate blocks ready to paste into LaTeX
    results/figures/*.png        the same plots as images for the repository
"""

from __future__ import annotations

import csv
import json
import os
import statistics as st
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

ORDER = ["dense", "dense_gated", "hybrid", "hybrid_ar"]
SHORT = {"dense": "Softmax", "dense_gated": "Softmax+Gate",
         "hybrid": "Hybrid", "hybrid_ar": "Hybrid+AttnRes"}


def load(path="results/pilot.json"):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def group(runs):
    out = {}
    for r in runs:
        out.setdefault(r["variant"], []).append(r)
    return out


def mean_sd(vals):
    vals = [v for v in vals if v == v]
    if not vals:
        return float("nan"), float("nan")
    if len(vals) == 1:
        return vals[0], 0.0
    return st.mean(vals), st.stdev(vals)


def build_summary(data):
    runs = group(data["runs"])
    lengths = [e["seq_len"] for e in data["runs"][0]["evals"]]
    rows = []
    for v in ORDER:
        if v not in runs:
            continue
        for i, L in enumerate(lengths):
            acc = [r["evals"][i]["accuracy"] for r in runs[v]]
            sink = [r["evals"][i]["sink_mass"] for r in runs[v]]
            sinkmax = [r["evals"][i]["sink_mass_max_layer"] for r in runs[v]]
            act = [r["evals"][i]["max_activation"] for r in runs[v]]
            ent = [r["evals"][i]["attn_entropy"] for r in runs[v]]
            rec = [r["evals"][i]["recency_gap"] for r in runs[v]]
            q = [[r["evals"][i][f"acc_q{k}"] for r in runs[v]] for k in range(1, 5)]
            am, asd = mean_sd(acc)
            row = {
                "variant": v, "label": SHORT[v], "seq_len": L,
                "acc_mean": am, "acc_sd": asd,
                "sink_mean": mean_sd(sink)[0], "sink_sd": mean_sd(sink)[1],
                "sink_max_layer": mean_sd(sinkmax)[0],
                "max_activation": mean_sd(act)[0],
                "attn_entropy": mean_sd(ent)[0],
                "recency_gap": mean_sd(rec)[0], "recency_sd": mean_sd(rec)[1],
                "n_examples": runs[v][0]["evals"][i]["n_examples"],
                "seeds": len(runs[v]),
            }
            for k in range(4):
                row[f"acc_q{k + 1}"] = mean_sd(q[k])[0]
            rows.append(row)
    return rows, lengths


def write_csv(rows, path, fields=None):
    if not rows:
        return
    fields = fields or list(rows[0].keys())
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def pgf_block(name, pairs, fmt="{:.0f} {:.4f}"):
    inner = " ".join("(" + fmt.format(a, b) + ")" for a, b in pairs)
    inner = inner.replace(" ", ", ", 0)
    coords = " ".join(f"({a}, {b:.4f})" for a, b in pairs)
    return f"% {name}\n\\addplot coordinates {{{coords}}};\n"


def main():
    data = load()
    rows, lengths = build_summary(data)
    write_csv(rows, "results/summary.csv")

    # Depth profiles.
    prof_rows = []
    runs = group(data["runs"])
    for v in ORDER:
        if v not in runs:
            continue
        for L in runs[v][0]["depth_profile"]:
            n_pts = len(runs[v][0]["depth_profile"][L])
            for j in range(n_pts):
                d = runs[v][0]["depth_profile"][L][j]["depth"]
                accs = [r["depth_profile"][L][j]["acc"] for r in runs[v]]
                prof_rows.append({"variant": v, "label": SHORT[v],
                                  "seq_len": int(L), "depth": d,
                                  "acc": mean_sd(accs)[0]})
    write_csv(prof_rows, "results/depth_profile.csv")

    # Coordinate blocks for the paper.
    lines = ["% Generated by scripts/make_figures.py. Paste into pgfplots.\n"]
    lines.append("\n%% accuracy against evaluation length\n")
    for v in ORDER:
        pts = [(r["seq_len"], r["acc_mean"]) for r in rows if r["variant"] == v]
        if pts:
            lines.append(f"% {SHORT[v]}\n" + "\\addplot coordinates {" +
                         " ".join(f"({a},{b:.4f})" for a, b in pts) + "};\n")
    lines.append("\n%% sink mass against evaluation length\n")
    for v in ORDER:
        pts = [(r["seq_len"], r["sink_mean"]) for r in rows if r["variant"] == v]
        if pts:
            lines.append(f"% {SHORT[v]}\n" + "\\addplot coordinates {" +
                         " ".join(f"({a},{b:.4f})" for a, b in pts) + "};\n")
    lines.append("\n%% recall against needle depth\n")
    for L in sorted({r["seq_len"] for r in prof_rows}):
        lines.append(f"%% length {L}\n")
        for v in ORDER:
            pts = [(r["depth"], r["acc"]) for r in prof_rows
                   if r["variant"] == v and r["seq_len"] == L]
            if pts:
                lines.append(f"% {SHORT[v]} at {L}\n" + "\\addplot coordinates {" +
                             " ".join(f"({a:.2f},{b:.4f})" for a, b in pts) + "};\n")
    with open("results/pgfplots.txt", "w", encoding="utf-8") as f:
        f.writelines(lines)

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        os.makedirs("results/figures", exist_ok=True)

        fig, ax = plt.subplots(1, 2, figsize=(9, 3.4))
        for v in ORDER:
            pts = [(r["seq_len"], r["acc_mean"]) for r in rows if r["variant"] == v]
            if pts:
                ax[0].plot(*zip(*pts), marker="o", label=SHORT[v])
            pts = [(r["seq_len"], r["sink_mean"]) for r in rows if r["variant"] == v]
            if pts:
                ax[1].plot(*zip(*pts), marker="s", label=SHORT[v])
        ax[0].set_xscale("log", base=2); ax[0].set_xlabel("evaluation length")
        ax[0].set_ylabel("needle recall"); ax[0].grid(alpha=.3); ax[0].legend(fontsize=7)
        ax[1].set_xscale("log", base=2); ax[1].set_xlabel("evaluation length")
        ax[1].set_ylabel("attention on position zero"); ax[1].grid(alpha=.3)
        fig.tight_layout(); fig.savefig("results/figures/length_scaling.png", dpi=160)

        fig2, ax2 = plt.subplots(figsize=(5, 3.2))
        Lmax = max(r["seq_len"] for r in prof_rows)
        for v in ORDER:
            pts = [(r["depth"], r["acc"]) for r in prof_rows
                   if r["variant"] == v and r["seq_len"] == Lmax]
            if pts:
                ax2.plot(*zip(*pts), marker="o", label=SHORT[v])
        ax2.set_xlabel(f"needle depth at length {Lmax}")
        ax2.set_ylabel("recall"); ax2.grid(alpha=.3); ax2.legend(fontsize=7)
        fig2.tight_layout(); fig2.savefig("results/figures/depth_profile.png", dpi=160)
        print("wrote results/figures/*.png")
    except Exception as exc:                      # pragma: no cover
        print("matplotlib step skipped:", exc)

    print("wrote results/summary.csv, results/depth_profile.csv, "
          "results/pgfplots.txt")
    print()
    hdr = f"{'variant':>16} {'len':>6} {'acc':>14} {'sink':>8} {'maxact':>8} {'recency':>8}"
    print(hdr)
    for r in rows:
        print(f"{r['label']:>16} {r['seq_len']:>6} "
              f"{r['acc_mean']:.3f} +/- {r['acc_sd']:.3f} "
              f"{r['sink_mean']:>8.3f} {r['max_activation']:>8.1f} "
              f"{r['recency_gap']:>+8.3f}")


if __name__ == "__main__":
    main()
